# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MSC_msg

class OpType(object):
    time_query = 0
    time_distribution = 1
    time_learn = 2
    machine_query = 3
    machine_report = 4
    task_order = 5
    task_completion = 6

