apiVersion: apps/v1
kind: Deployment
metadata:
 labels: null
 name: taskscheduler
 namespace: core
spec:
 replicas: 1
 selector:
   matchLabels:
     app: taskscheduler
 template:
   metadata:
     labels:
       app: taskscheduler
   spec:
     containers:
     - image: cxd9974/msc_taskscheduler:latest
       name: taskscheduler
       ports:
       - containerPort: 5672
       env:
       - name: USERNAME
         valueFrom:
           secretKeyRef:
             name: rmq-default-user
             key: username
       - name: PASSWORD
         valueFrom:
           secretKeyRef:
             name: rmq-default-user
             key: password
         ##set PYTHONIOENCODING=UTF-8
       - name: PYTHONIOENCODING
         value: "UTF-8"
         ###debug logs, enable 2 lines below to see print from python, disable on production
       - name: PYTHONUNBUFFERED
         value: "1"