apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: web
  name: web
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: core
  name: core
---
#check more at https://www.rabbitmq.com/kubernetes/operator/using-operator.html
#and https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/production-ready
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rmq
  namespace: core
  labels:
    app: rmq
spec:
####### if we want to expose rmq outside the cluster
  service:
    type: LoadBalancer
####### if we want to limit resource...
#  replicas: 1
#  resources:
#    requests:
#      cpu: 500m
#      memory: 1Gi
#    limits:
#      cpu: 800m
#      memory: 1Gi
---
###### next, get a secret from docker login 
## kubectl create secret generic regcred     --from-file=.dockerconfigjson=/home/c00251686/.docker/config.json     --type=kubernetes.io/dockerconfigjson -n web
## kubectl create secret generic regcred     --from-file=.dockerconfigjson=/home/c00251686/.docker/config.json     --type=kubernetes.io/dockerconfigjson -n core
##