apiVersion: v1
kind: Service
metadata:
  name: webplayer
  namespace: web
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3000
  selector:
    app: webplayer
  type: LoadBalancer
  externalIPs: [10.131.36.27]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: null
  name: webplayer
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webplayer
  template:
    metadata:
      labels:
        app: webplayer
    spec:
      containers:
      - image: cxd9974/msc_web:latest
        name: webplayer
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_REQURL
          value: "adc.core:60008"
      imagePullSecrets:
      - name: regcred
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webplayer-ingress
  namespace: web
spec:
  rules:
  - host: mynodeapp.com
    http:
      paths:
      - backend:
          service:
            name: webplayer
            port:
              number: 8080
        path: /test
        pathType: Prefix
